#ifndef _CONSTANTS_H
#define _CONSTANTS_H

#define	BUFF_SIZE_LONG	1000000
#define	BUFF_SIZE_SHORT	512

#define	MODEL_STATUS_UNKNOWN	0
#define	MODEL_STATUS_EST	1
#define	MODEL_STATUS_ESTC	2
#define	MODEL_STATUS_INF	3
#define MODEL_STATUS_PREPROCESS 4
#define MODEL_STATUS_RANKING 5

#endif

